//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ems_onscene.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSBagCheck
    {
        public int Id { get; set; }
        public int BagCheckTitle { get; set; }
        public string Detail { get; set; }
    
        public virtual EMSBagCheckDetail EMSBagCheckDetail { get; set; }
    }
}
