//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ems_onscene.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSBagCheckDetail
    {
        public int Id { get; set; }
        public Nullable<int> EMSBagCheckId { get; set; }
        public string Detail { get; set; }
    
        public virtual EMSBagCheck EMSBagCheck { get; set; }
    }
}
