//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ems_onscene.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSContent
    {
        public int id { get; set; }
        public string contenttype { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string registid { get; set; }
        public System.DateTime registdt { get; set; }
        public string updateid { get; set; }
        public Nullable<System.DateTime> updatedt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ContentType ContentType1 { get; set; }
    }
}
