//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ems_onscene.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSMessage
    {
        public int id { get; set; }
        public string MessageFrom { get; set; }
        public string MessageTo { get; set; }
        public string MessageTitle { get; set; }
        public string MessageText { get; set; }
        public System.DateTime MessageTimeSent { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
    }
}
