//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ems_onscene.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMSOrganization
    {
        public int Id { get; set; }
        public string OrganizationName { get; set; }
        public string LogoImageUrl { get; set; }
        public string HomepageImageUrl { get; set; }
    }
}
