//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ems_onscene.Models.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Rank { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual EMSRole EMSRole { get; set; }
    }
}
